# Generated by Django 4.2.16 on 2024-11-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamkor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='video',
        ),
    ]
